apiVersion: v1
kind: Service
metadata:
  name: crm-web
  namespace: crm
  labels:
    app.kubernetes.io/name: crm-web
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: crm-monorepo
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: crm-web


