apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: crm-operators

resources:
  - postgresql-cluster.yaml
  - redis-cluster.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: crm

